queue: 'Hosted Linux Preview'
steps:
- alwaysRun: false
  condition: succeeded()
  continueOnError: false
  displayName: Use Python 3.x
  enabled: true
  environment: {}
  inputs: {addToPath: 'true', architecture: x64, versionSpec: 3.x}
  task: {definitionType: task, id: 33c63b11-352b-45a2-ba1b-54cb568a29ca, versionSpec: 0.*}
  timeoutInMinutes: 0
- alwaysRun: false
  condition: succeeded()
  continueOnError: false
  displayName: Bash Script
  enabled: true
  environment: {}
  inputs: {arguments: '', failOnStderr: 'false', filePath: '', script: 'pip install
      pytest numpy

      pytest tests -s -v', targetType: inline, workingDirectory: ''}
  task: {definitionType: task, id: 6c731c3c-3c68-459a-a5c9-bde6e6595b5b, versionSpec: 3.*}
  timeoutInMinutes: 0
